version: "3.2"
services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile.prod
    image: simple-report-api-build
    ports:
      - "8080:8080"
  locust-brain:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust-brain:8089
  locust-worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-brain
